name: Lint
on:
  workflow_dispatch:
  push:

jobs:
  lint:
    name: code linting
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/contactspace

    steps:
      # Checkout your code
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate with GitHub Packages
        run: git config --global url."https://x-oauth-basic:${{ secrets.GH_PAT }}@github.com/".insteadOf "https://github.com/"

      # Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24
          check-latest: true

      # Cache Go modules and build cache
      - name: Cache Go modules and build artifacts
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download Dependencies
        run: go mod tidy

      # Cache `golangci-lint` binary for faster builds
      - name: Cache golangci-lint
        uses: actions/cache@v3
        with:
          path: ~/.cache/golangci-lint
          key: ${{ runner.os }}-golangci-lint-cache
          restore-keys: |
            ${{ runner.os }}-golangci-lint-

      # Install golangci-lint
      - name: Install golangci-lint
        run: |
          if ! command -v golangci-lint &> /dev/null; then
            curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.1.6
          fi

      # Linting
      - name: Linting
        run: |
          make lint
